### ISSUE TITLE
Incorrect repeat expiry date for calendar exports

### ISSUE THREAD

**Issue by jackburkhardt** [dilanx/paper.nu#33]
Noticed a small bug when exporting class schedules as .ics format and then attempting to import into a calendar software. Once imported to the calendar, the end date for the event repeat doesn't match the actual quarter end. Tested with the calendar attached below, and the issue is present in both Google Calendar and Outlook imports.

Google Calendar:
![image](https://user-images.githubusercontent.com/43016465/210152022-032d0544-f7a6-4052-b0bf-1eb595135753.png)

Outlook:
![image](https://user-images.githubusercontent.com/43016465/210152027-daa04fc3-f225-4409-86ce-724eb5b0fbc9.png)

Opening up the ICS file, it looks like the UNTIL date is malformed causing calendar software to improperly parse the end date, leading to the issue here. Plugging it into an [iCalendar Validator](https://icalendar.org/validator.html) seems to confirm: 
![image](https://user-images.githubusercontent.com/43016465/210151856-497dfd8d-92fd-436c-950d-e11f10f69f97.png)

My .ics file dump: https://hastebin.com/hehopedequ.apache

Hope this helps!

**Comment by dilanx** [comment]
Yeah it seems like there's a bunch of stuff going wrong with the calendar export feature. I'll look into it soon. Thanks for the detailed info it's super helpful!

**Comment by dilanx** [comment]
It turns out I didn't pad the numbers in the date properly, so it ended up being `2023311` where it should have been `20230311`. This should be fixed in 2.1.3 along with the other calendar exporting issue #121.
